name: Housekeeping CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  doc:
    name: Check Markdown links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Markdown dead link checker
        uses: AlexanderDokuchaev/md-dead-link-check@v1.2.0
        