name: Monkey Interpreter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Run tests with coverage
        run: |
          cd monkey/interpreter  # Navigate to the project directory
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: monkey/interpreter/coverage.out

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-go@v2
        with:
          files: ./monkey/interpreter/coverage.svg

      - name: Upload coverage badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: ./monkey/interpreter/coverage.svg
    