name: Regex Engine CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'regex_engine/**'    
  pull_request:
    branches: [ "main" ]
    paths:
      - 'regex_engine/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Run tests in 'regex_engine'
      run: |
        cd regex_engine
        go test ./...