name: Web App Bis CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web_app_bis/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web_app_bis/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Run tests in 'web_app_bis'
      run: |
        cd web_app_bis
        go test ./...
